---

# influxdb
# see:
# - http://influxdb.com/download/
# - http://influxdb.com/docs/v0.9/introduction/installation.html

- name: create pkg dir
  file: 
    path: /home/{{rem_user}}/.pkg 
    state: directory 
    group: "{{rem_user}}"
    owner: "{{rem_user}}"
  when: ansible_hostname == influxdb_hostname

- name: get deb file
  become: no
  get_url: 
    url: http://dl.influxdata.com/influxdb/releases/influxdb_{{influx_version}}_amd64.deb
    dest: /home/{{rem_user}}/.pkg/influxdb_{{influx_version}}_amd64.deb
  when: ansible_hostname in influx_hosts

- name: install package
  apt: deb=/home/{{rem_user}}/.pkg/influxdb_{{influx_version}}_amd64.deb
  when: ansible_hostname in influx_hosts

- name: install python dependencies
  become: yes
  pip: name={{item}}
  with_items:
    - influxdb

- name: setup logrotate
  become: true
  template:
    src: logrotate
    dest: /etc/logrotate.d/influxdb
  when: ansible_hostname in influx_hosts

- name: install config file
  become: true
  template: 
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root 
    group: root
  notify: restart influxdb
  when: ansible_hostname in influx_hosts

- name: setup admin user
  command: influx -execute "create user admin with password 'admin' with all privileges"
  ignore_errors: true
  when: ansible_hostname in influx_hosts

- name: create database
  influxdb_database:
    username: "admin"
    password: "admin"
    hostname: "localhost"
    database_name: "{{ item }}"
    state: present
  with_items:
    - telegraf
    - stocks
    - ping
    - influx
    - cronlog
    - bootlog
    - backups
    - weather
    - bugm_log
    - bugm_stats
  when: ansible_hostname in influx_hosts
