---
# see https://github.com/neovim/neovim/releases

# nvim_vsn: v0.3.0  superseded 2018 Jul 18 Wed
# nvim_vsn: v0.3.1  superseded 2019 Jan 05 Sat
# nvim_vsn: v0.3.3  superseded 2019 Jan 31 Thu
# nvim_vsn: v0.3.4  superseded 2019 Aug 08 Thu
# nvim_vsn: v0.4.2  superseded 2020 Feb 14 Fri
# nvim_vsn: v0.4.3  superseded 2020 Aug 22 Sat
# nvim_vsn: v0.4.4  superseded 2021 May 26 Wed
# nvim_vsn: v0.5.0  superseded 2021 Aug 13 Fri
# nvim_vsn: v0.5.1  superseded 2021 Dec 02 Thu
# nvim_vsn: v0.6.0  superseded 2022 Jan 26 Wed
# nvim_vsn: v0.7.0  superseded 2022 Sep 09 Fri
# nvim_vsn: v0.7.2  superseded 2022 Sep 30 Fri
# nvim_vsn: v0.8.0  superseded 2022 Nov 15 Tue
# nvim_vsn: v0.8.1  superseded 2022 Dec 30 Fri
# nvim_vsn: v0.8.2  superseded 2023 Feb 19 Sun
# nvim_vsn: v0.8.3  superseded 2023 Apr 07 Fri
# nvim_vsn: v0.9.0  superseded 2023 May 30 Tue
# nvim_vsn: v0.9.1  superseded 2023 Sep 07 Thu
# nvim_vsn: v0.9.2  superseded 2023 Aug 09 Wed 
# nvim_vsn: v0.9.4  superseded 2024 Jan 03 Wed
# nvim_vsn: v0.9.5  superseded 2024 May 16 Thu
# nvim_vsn: v0.10.0 superseded 2024 Jul 24 Wed
# nvim_vsn: v0.10.1 superseded 2024 Oct 03 Thu
# nvim_vsn: v0.10.2 superseded 2025 Mar 26 Wed
# nvim_vsn: v0.10.4 superseded 2025 Apr 19 Sat
# nvim_vsn: v0.11.0 superseded 2025 May 27 Tue
# nvim_vsn: v0.11.1 superseded 2025 May 30 Fri
# nvim_vsn: v0.11.2 superseded 2025 Jul 20 Sun
# nvim_vsn: v0.11.3 superseded 2025 Aug 31 Sun
# nvim_vsn: v0.11.4 superseded 2025 Nov 02 Sun
nvim_vsn: v0.11.5
