---

# postgres
# see http://wiki.postgresql.org/wiki/Apt
# see http://wiki.postgresql.org/wiki/Apt/FAQ

- name: add postgres repository ARM7
  template: src=pgdg.list dest=/etc/apt/sources.list.d/pgdg.list
  notify: 
    - apt-cache update

- name: import postgres repository key ARM7
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  notify: 
    - apt-cache update

- name: remove outdated packages ARM7
  apt: pkg={{item}} state=absent purge=yes
  with_items:
    - postfix
    - postgresql

- name: remove old postgres versions ARM7
  apt: pkg={{item}} state=absent purge=yes
  with_items: '{{old_postgres_versions}}'

- name: remove old postgres config directories ARM7
  file: path=/etc/postgresql/{{item}} state=absent
  with_items: '{{old_postgres_versions}}'

- name: flush all outstanding handlers ARM7
  meta: flush_handlers

- name: install postgres packages ARM7
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - libpq-dev 
    - postgresql-{{postgres_version}}
    - postgresql-contrib-{{postgres_version}}

# - name: force port 5432
#   lineinfile:
#     dest:   /etc/postgresql/{{postgres_version}}/main/postgresql.conf
#     line:   "port = 5432"
#     regexp: "^port ="
#   notify:
#     - restart postgres 
#
# - name: security settings for user creation
#   lineinfile: 
#     state:  present 
#     dest:   /etc/postgresql/{{postgres_version}}/main/pg_hba.conf 
#     line:   "local all postgres trust" 
#     regexp: "^local +all +postgres +peer" 
#     backrefs: yes
#   notify:
#     - restart postgres 
#
# - name: security settings for database creation
#   lineinfile: 
#     state:  present 
#     dest:   /etc/postgresql/{{postgres_version}}/main/pg_hba.conf 
#     line:   "local all all trust" 
#     regexp: "^local +all +all +peer" 
#     backrefs: yes
#   notify:
#     - restart postgres 
#
# - name: flush all outstanding handlers
#   meta: flush_handlers
#
# - name: create template_base database
#   postgresql_db: 
#     name:       template_base 
#     encoding:   UTF8 
#     lc_collate: en_US.UTF-8 
#     lc_ctype:   en_US.UTF-8 
#     template:   template0
#
# - name: install python utilities
#   pip:
#     name: "{{ item }}"
#   with_items:
#     - psycopg2
