---

# nodejs

# nodejs installation has moved from 'chris-lea' to 'nodesource'
# see https://github.com/nodesource/distributions#installation-instructions

- name: remove old PPA
  apt_repository: repo=ppa:chris-lea/node.js state=absent

- name: add repository key
  apt_key: 
    url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    state: present

- name: remove old repositories
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{item}}.x {{ansible_distribution_release}} main'
    state: absent
    update_cache: yes
  with_items:
    - 4
    - 5

- name: add repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{item}}.x {{ansible_distribution_release}} main'
    state: present
    update_cache: yes
  with_items:
    - 6

- name: add nodejs and npm
  apt: pkg={{item}} state=latest force=yes
  with_items:
    - nodejs

- name: npm packages
  become: yes
  npm: name={{item}} state=latest global=yes
  with_items:
    - bower
    - brunch
    - coffee-script
    - webpack
    - webpack-dev

