---

# Asdfbun 

# Set global version in ~/.tool-versions

- name: "install plugins for {{gen_user}}"
  command: "bash -ilc 'asdf plugin add {{ item.name }} {{item.repo}}'"
  args:
    creates: "/home/{{gen_user}}/.asdf/plugins/{{ item.name }}"
    chdir: "/home/{{gen_user}}"
  become_user: "{{ gen_user }}"
  ignore_errors: true
  with_items:
    - { name: bun   , repo: ""}

- name: update asdf bun plugin 
  command: "bash -ilc 'asdf plugin update bun'"
  become_user: "{{ gen_user }}"

- name: install asdf_bun
  command: "bash -ilc 'asdf install bun {{ bun_vsn }}'"
  args:
    creates: "/home/{{gen_user}}/.asdf/installs/bun/{{ bun_vsn }}"
    chdir: "/home/{{ gen_user }}"
  become_user: "{{ gen_user }}"

- name: Update .tool-versions (only on the control host) 
  lineinfile:
    path: "/home/aleak/util/base_util/cfg/_tool-versions"
    regexp: '^bun'
    line: "bun {{ bun_vsn }}"
    create: yes
  delegate_to: localhost

- name: reshim
  become_user: "{{gen_user}}"
  command: "bash -ilc 'asdf reshim bun {{bun_vsn}}'"
