---
# grafana_version: 2.0.2 superseded 2015-08-18
# grafana_version: 2.1.1 superseded 2015-10-28
# grafana_version: 2.5.0 superseded 2015-12-14
# grafana_version: 2.6.0 superseded 2016-04-02
# grafana_version: 3.0.0 superseded 2016-05-12
# grafana_version: 3.0.1 superseded 2016-05-23
# grafana_version: 3.0.3 superseded 2016-07-12
# grafana_version: 3.1.0 superseded 2016-11-09
# grafana_version: 3.1.1 superseded 2016-11-22
# grafana_version: 4.0.B superseded 2016-11-29
# grafana_version: 4.0.0 superseded 2016-12-08
# grafana_version: 4.0.2 superseded 2017-03-22
# grafana_version: 4.2.0 superseded 2017-05-24
# grafana_version: 4.3.1 superseded 2017-11-02
# grafana_version: 4.6.1 superseded 2017-11-16
# grafana_version: 4.6.2 superseded 2018-02-08
grafana_version: 5.0.0-beta1
