---

# Util/Date

- name: create a util directory
  become: false
  file: 
    path: /home/{{gen_user}}/util 
    state: directory 
    group: "{{gen_user}}" 
    owner: "{{gen_user}}"

- name: remove the deck_util directory
  file:
    path: /home/{{gen_user}}/util/deck_util
    state: absent

- name: install deck_util for {{gen_user}}
  become_user: "{{gen_user}}"
  git:
    repo:   "{{filehost}}:Git/Util/deck_util.git"
    dest:   /home/{{gen_user}}/util/deck_util
    update: yes
