---

# cli_tzone
 
- name: get current timezone
  shell: cat /etc/timezone
  register: current_zone
  changed_when: false
 
- name: update timezone if necessary
  become: true
  when: {{ current_zone.stdout }} != "{{my_tzone}}"
  copy: 
    content: "{{my_tzone}}"
    dest:    /etc/timezone
    backup:  yes
  notify:
    - update timezone

