---

# certbot

# this just installs the lets_encrypt certbot client
# 
# after the application is installed and nginx is configured,
# provision the SSL certs with the certbot command

- name: install certbot ppa
  become: true
  apt_repository: repo={{item}} 
  with_items:
    - ppa:certbot/certbot

- name: install 
  become: true
  apt:  pkg={{item}} state=latest install_recommends=yes
  with_items:
    - software-properties-common
    - python-certbot-nginx

- name: create SSL certs
  shell: "/home/{{rem_user}}/util/pdev_util/bin/run_certbot {{inventory_hostname}} {{subdomains}}"

