---
# elixir_version: 1.1.0      superseded 2015 Sep 29
# elixir_version: 1.1.1      superseded 2016 Jan 01
# elixir_version: 1.2.0      superseded 2016 May 07
# elixir_version: 1.2.5      superseded 2016 Jun 07
# elixir_version: 1.2.6      superseded 2016 Jun 21
# elixir_version: 1.3.0      superseded 2016 Sep 09
# elixir_version: 1.3.2      superseded 2016 Sep 19
# elixir_version: 1.3.3      superseded 2016 Oct 18
# elixir_version: 1.3.4      superseded 2017 Jan 04
# elixir_version: 1.4.0      superseded 2017 Jan 31
# elixir_version: 1.4.1      superseded 2017 Jun 22
# elixir_version: 1.4.5      superseded 2017 Jul 25
# elixir_version: 1.5.0      superseded 2017 Dec 05
# elixir_version: 1.5.2      superseded 2018 Jan 18
# elixir_version: 1.6.0      superseded 2018 Feb 28
# elixir_version: 1.6.2      superseded 2018 Mar 09
elixir_version: 1.6.3
