---

# ubigraph install

- name: install support software
  become: yes
  apt:  pkg={{item}} state=latest
  with_items:
    - freeglut3

- name: create package cache dir
  file: path=/home/{{rem_user}}/.pkg state=directory group={{rem_user}} owner={{rem_user}}

- name: get package
  become: no
  get_url:
    url:  http://ubietylab.net/files/alpha-{{ubigraph_version}}/UbiGraph-alpha-{{ubigraph_version}}-Linux64-Ubuntu-8.04.tgz 
    dest: /home/{{rem_user}}/.pkg/ubigraph-{{ubigraph_version}}.tgz
    force: no

- name: untar package
  become: no
  shell: tar -xf ubigraph-{{ubigraph_version}}.tgz ; mv UbiGraph-alpha-{{ubigraph_version}}-Linux64-Ubuntu-8.04 ubigraph-{{ubigraph_version}}
  args:
    chdir:   /home/{{rem_user}}/.pkg 
    creates: /home/{{rem_user}}/.pkg/ubigraph-{{ubigraph_version}}

- name: installation symlinks
  become: yes
  file: src=/home/{{rem_user}}/.pkg/ubigraph-{{ubigraph_version}}/bin/{{item}} dest=/usr/local/bin/{{item}} state=link
  with_items:
    - ubigraph_server
        
