---

# note: tmux.conf is in ~/util/base_util/cfg/_tmux.conf

- name: install tmux executable
  become: true
  copy:
    src: tmux-{{ansible_architecture}}-{{tmux_version}}
    dest: /usr/bin/tmux
    mode: "a+rx"

# tmate - see tmate.io

# - name: add TMATE PPA
#   become: true
#   apt_repository: repo=ppa:tmate.io/archive 
#   when: is_x86_64
#
# - name: install TMATE
#   become: true
#   apt:  pkg={{item}} state=latest
#   with_items:
#     - tmate
#   when: is_x86_64
