---

# phantomjs

- name: install dependencies
  become: true
  apt:  pkg={{item}} install_recommends=no
  with_items:
    - fontconfig
    - libfontconfig

- name: install phantomjs
  copy: src={{item}} dest=/usr/local/bin/{{item}} mode="a+rx"
  become: true
  with_items:
    - phantomjs198
    - phantomjs211
