---

# packages for RPI

- name: install base packages
  become: true
  apt:  pkg={{item}} state=latest install_recommends=no
  with_items:
    - python-pip                 # required by ansible
    - python-dev                 # required by ansible
    - python-virtualenv          # required by ansible
    - build-essential            # compile tools
    - dnsutils                   # dnsutils
    - git-core                   # git
    - aptitude                   # package manager
    - cmake                      # required by libgit2/rugged
    - libicu-dev                 # development lib
    - htop                       # monitoring utility
    - atop                       # monitoring utility
    - ncdu                       # monitoring utility
    - nmon                       # monitoring utility
    - iftop                      # monitoring utility
    - dstat                      # monitoring utility
    - iotop                      # monitoring utility
    - nload                      # monitoring utility
    - sysstat                    # monitoring utility
    - libcurl4-openssl-dev       # development lib
    - libevent-dev               # development lib
    - libncurses5-dev            # development lib
    - libxml2-dev                # development lib
    - libreadline-dev            # development lib
    - libssl-dev                 # development lib
    - libxslt1-dev               # development lib
    - zlib1g-dev                 # development lib
    - multitail                  # log file monitoring
    - tree                       # cli utility
    - curl                       # cli utility
    - httpie                     # cli utility
    - wget                       # cli utility
    - unzip                      # cli utility
    - zip                        # cli utility
    - checkinstall               # builds debian packages
    - libxt6                     # needed for VIM
    - libsm6                     # needed for VIM
    - libxext6                   # needed for VIM

- name: remove packages
  become: true
  apt: pkg={{item}} state=absent
  with_items:
    - whoopsie        # ubuntu bug reporter

