---
# golang_vsn: 1.13.3  superseded 2020 Jun 10 Wed
# golang_vsn: 1.14.4  superseded 2022 Oct 25 Tue
# golang_vsn: 1.19.2  superseded 2024 Oct 06 Sun
# golang_vsn: 1.23.2  superseded 2025 Apr 01 Tue
# golang_vsn: 1.24.2  superseded 2026 Feb 27 Fri
golang_vsn: 1.26.0

