---

# ----- ELIXIR
# ex_vsn: 1.1.0          superseded 2015 Sep 29 Tue 
# ex_vsn: 1.2.0          superseded 2016 May 07 Sat
# ex_vsn: 1.3.0          superseded 2016 Sep 09 Fri
# ex_vsn: 1.4.0          superseded 2017 Jan 31 Tue
# ex_vsn: 1.5.0          superseded 2017 Dec 05 Tue
# ex_vsn: 1.6.0          superseded 2018 Feb 28 Wed
# ex_vsn: 1.7.0          superseded 2018 Jul 27 Fri
# ex_vsn: 1.8.0          superseded 2019 Jan 30 Wed
# ex_vsn: 1.9.0          superseded 2019 Oct 12 Sat
# ex_vsn: 1.10.0         superseded 2020 Mar 04 Wed
# ex_vsn: 1.11.0-otp-23  superseded 2020 Oct 19 Mon
# ex_vsn: 1.12.1-otp-24  superseded 2021 Jul 01 Thu
# ex_vsn: 1.13.3-otp-24  superseded 2022 Sep 09 Fri
# ex_vsn: 1.14.0-otp-25  superseded 2022 Nov 07 Mon
# ex_vsn: 1.15.0-otp-25  superseded 2023 Jun 30 Fri 
# ex_vsn: 1.16.0-otp-26  superseded 2024 Jan 31 Wed
# ex_vsn: 1.17.1-otp-27  superseded 2024 Aug 02 Fri
# ex_vsn: 1.18.0-otp-27  superseded 2025 Jan 03 Fri
# ex_vsn: 1.19.1-otp-28  superseded 2025 Nov 02 Sun
ex_vsn: 1.19.5-otp-28

# ----- PHOENIX / mix hex.info phx_new
# https://github.com/phoenixframework/phoenix/tags
#
# phx_vsn: 1.0.3      superseded 2015 Sep 29 Tue  
# phx_vsn: 1.1.0      superseded 2016 Jan 08 Fri   
# phx_vsn: 1.3.0      superseded 2018 Nov 07 Wed
# phx_vsn: 1.4.0      superseded 2019 Apr 29 Mon
# phx_vsn: 1.5.1      superseded 2021 Feb 17 Wed
# phx_vsn: 1.6.4      superseded 2022 Jan 04 Tue
# phx_vsn: 1.7.0      superseded 2023 Mar 11 Sat 
# phx_vsn: 1.8.0      superseded 2025 Oct 18 Sat
# phx_vsn: 1.8.2      superseded 2025 Dec 11 Thu
# phx_vsn: 1.8.3      superseded 2026 Feb 26 Thu
phx_vsn: 1.8.4

# ----- TABLEAU / mix hex.info tableau_new 
# tblu_vsn: 1.0.2     superseded 2024 May 19 Sun 
# tblu_vsn: 1.1.0     superseded 2024 Jun 17 Mon 
# tblu_vsn: 1.2.0     superseded 2024 Dec 03 Tue
# tblu_vsn: 1.4.1     superseded 2025 Jul 18 Fri
# tblu_vsn: 1.5.1     superseded 2025 Oct 18 Sat
tblu_vsn: 2.0.1
  
# ----- IGNITER / mix hex.info igniter_new
# igniter_vsn: 0.2.1  superseded 2024 Jul 25 Thu
# igniter_vsn: 0.3.0  superseded 2024 Oct 05 Sat
# igniter_vsn: 0.4.8  superseded 2024 Dec 11 Wed
# igniter_vsn: 0.5.23 superseded 2025 Mar 27 Thu
# igniter_vsn: 0.5.32 superseded 2026 Jan 21 Wed
igniter_vsn: 0.5.33
