---

# setup_ssh
#
# invoke with:
# - {role: setup_ssh, rem_user: "name"}

- name: config ssh timeout for {{rem_user}}
  lineinfile: 
    dest: /home/{{rem_user}}/.ssh/config 
    state: present 
    regexp: "ServerAliveInterval" 
    line: "ServerAliveInterval 20" 
    create: yes

- name: config ssh timeout for {{rem_user}}
  lineinfile: 
    dest:   /home/{{rem_user}}/.ssh/config 
    state:  present 
    regexp: "KeepAlive" 
    line:   "KeepAlive yes" 
    create: yes

# - name: ssh keys for {{rem_user}}
#   authorized_key:
#     user: "{{rem_user}}"
#     key: "{{ lookup('file', '/home/aleak/.ssh/id_rsa.pub') }}"
