---

# rpi_hotspot
# see http://elinux.org/RPI-Wireless-Hotspot

- name: install support packages
  become: true
  apt:  pkg={{item}} state=latest install_recommends=no
  with_items:
    - hostapd      # access point demon
    - udhcpd       # dhcp demon
    - bmon         # in-console bandwidth monitor
    - iw           # wifi configurator
    - bridge-utils # bridge-utils
    - iptables-persistent

- name: revert hostapd config if ansible has already been run
  become: true
  shell: if [ -f /usr/sbin/hostapd.backup ]; then mv /usr/sbin/hostapd.backup /usr/sbin/hostapd.stock; fi

- name: backup hostapd binary if it has not already been backed up
  become: true
  shell: if [ ! -f /usr/sbin/hostapd.stock ]; then cp -a /usr/sbin/hostapd /usr/sbin/hostapd.stock; fi
  
- name: Backup the hostapd init file
  become: true
  shell: if [ ! -f /etc/init.d/hostapd.backup ]; then mv /etc/init.d/hostapd /etc/init.d/hostapd.backup; fi

- name: install new hostapd init file
  become: true
  copy:
    src: hostapd-initfile
    dest: /etc/init.d/hostapd
    mode: "a+rx"

- name: install a bug-fix version of hostapd
  become: true
  copy: 
    src: hostapd
    dest: /usr/sbin/hostapd.new
    mode: "a+rx"

- name: fix an error in /etc/init.d/hostapd
  become: true
  lineinfile:
    dest:   /etc/init.d/hostapd
    line:   "DAEMON_CONF=/etc/hostapd/hostapd.conf"
    regexp: "^DAEMON_CONF="

- name: configure /etc/udhcpd.conf
  lineinfile: 
    dest:    /etc/udhcpd.conf
    line:    "{{ item.line }}" 
    regexp:  "{{ item.reg }}"
  with_items:
    - {reg: "^start"                 , line: "start 192.168.42.2"      }
    - {reg: "^end"                   , line: "end   192.168.42.20"     }
    - {reg: "^interface"             , line: "interface wlan0"         }
    - {reg: "^remaining"             , line: "remaining yes"           }
    - {reg: "^opt(ion)?[ |\t]+dns"   , line: "opt dns 8.8.8.8 4.2.2.2" }
    - {reg: "^opt(ion)?[ |\t]+subnet", line: "opt subnet 255.255.255.0"}
    - {reg: "^opt(ion)?[ |\t]+router", line: "opt router 192.168.42.1" } 
    - {reg: "^opt(ion)?[ |\t]+lease" , line: "opt lease 864000"        } 

- name: configure /etc/default/udhcpd
  become: true
  lineinfile:
    dest:   /etc/default/udhcpd
    regexp: '^#DHCPD_ENABLED'
    line:   'DHCPD_ENABLED="yes"'

- name: configure /etc/default/hostapd
  become: true
  lineinfile:
    dest:   /etc/default/hostapd
    regexp: '^DAEMON_CONF'
    line:   'DAEMON_CONF="/etc/hostapd/hostapd.conf"'

- name: update udhcpd init to bring up wlan0 before starting
  become: true
  shell: sudo sed -i s=^set\ -e=set\ -e'\n'ifup\ wlan0=g /etc/init.d/udhcpd

- name: update udhcpd init to touch leases file
  become: true
  shell: sudo sed -i s=^set\ -e=set\ -e'\n'touch\ /var/lib/misc/udhcpd.leases=g /etc/init.d/udhcpd   

- name: setup network interfaces
  become: true
  template: 
    src:  interfaces
    dest: /etc/network/interfaces

- name: set wlan0 static address
  become:  true
  shell: ifconfig wlan0 192.168.42.1

- name: configure hostapd.conf
  template:
    src:  hostapd.conf
    dest: /etc/hostapd/hostapd.conf

- name: turn on IP forwarding
  become: true
  shell: sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

- name: modprobe ip_tables
  become: true
  command: modprobe ip_tables

- name: enable ip_tables on reboot
  become: true
  lineinfile:
    dest: /etc/modules
    line: "ip_tables"

- name: enable NAT in the kernel 
  become: true
  shell: "{{item}}" 
  with_items:
    - "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
    - "iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
    - "iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT"

- name: enable IP forwarding on boot (/etc/sysctl.conf)
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv4.ip_forward=1" 
    regexp: "^net.ipv4.ip_forward"

- name: save IPTABLES settings
  become:  true
  shell: "{{item}}"
  with_items:
    - "sh -c 'iptables-save > /etc/iptables/rules.v4'"
    - "sh -c 'rm -f /etc/iptables.ipv4.nat'"
    - "sh -c 'ln -s /etc/iptables/rules.v4 /etc/iptables.ipv4.nat'"

- name: start the access point
  become:  true
  shell: "{{item}}" 
  with_items:
    - "service hostapd start"
    - "service udhcpd start"

- name: auto-start access point on Boot
  become:  true
  shell: "{{item}}" 
  with_items:
    - "update-rc.d hostapd enable"
    - "update-rc.d udhcpd enable"

