---

# telegraf

- name: create package cache dir
  file: path=/home/{{rem_user}}/.pkg state=directory group={{rem_user}} owner={{rem_user}}

- name: get deb file
  become: no
  get_url:
    url:  https://dl.influxdata.com/telegraf/releases/telegraf_{{telegraf_version}}_amd64.deb
    dest: /home/{{rem_user}}/.pkg/telegraf_{{telegraf_version}}_amd64.deb
    force: no
    validate_certs: no
  when: is_x86_64

- name: install package
  apt: deb=/home/{{rem_user}}/.pkg/telegraf_{{telegraf_version}}_amd64.deb
  when: is_x86_64

- name: get armhf executable
  become: no
  get_url:
    url:  https://dl.influxdata.com/telegraf/releases/telegraf-{{telegraf_version}}_linux_armhf.tar.gz
    dest: /home/{{rem_user}}/.pkg/telegraf-{{telegraf_version}}_linux_armhf.tar.gz
    force: no
    validate_certs: no
  when: is_arm7

- name: create executable directory
  file: 
    path:  /home/{{rem_user}}/.pkg/telegraf-{{telegraf_version}} 
    state: directory 
    group: "{{rem_user}}" 
    owner: "{{rem_user}}"
  when: is_arm7

- name: untar armhf executable
  become: no
  unarchive:
    src:  /home/{{rem_user}}/.pkg/telegraf-{{telegraf_version}}_linux_armhf.tar.gz
    dest: /home/{{rem_user}}/.pkg/telegraf-{{telegraf_version}}
    remote_src: True
  when: is_arm7

- name: create symlink
  become: yes
  file:
    src:  /home/{{rem_user}}/.pkg/telegraf-{{telegraf_version}}/telegraf/usr/bin/telegraf
    dest: /usr/bin/telegraf
    state: link 
  when: is_arm7

- name: install service file
  become: true
  template: 
    src:   telegraf.service
    dest:  /lib/systemd/system
    owner: root 
    group: root
    mode:  "a+r"
  notify: restart telegraf
  when: is_arm7

- name: create config directory
  become: true
  file: 
    path:  /etc/telegraf
    state: directory 
  when: is_arm7

- name: install base config
  become: true
  template: 
    src:   telegraf.conf
    dest:  /etc/telegraf/telegraf.conf 
    owner: root 
    group: root
    mode:  "a+r"
  notify: restart telegraf

- name: generate process list
  live_demons:
    candidates:
      - postgres
      - redis
      - nginx
      - memcached
      - influx
      - grafana
  register: live_procs

- name: install procstat configs 
  become: true
  template: 
    src:   telegraf_procstat.conf
    dest:  /etc/telegraf/telegraf.d/telegraf_procstat_{{item}}.conf 
    owner: root 
    group: root
    mode:  "a+r"
  notify: restart telegraf
  with_items: "{{ live_procs.list }}"

- name: install demon configs
  become: true
  template: 
    src:   telegraf_{{item}}.conf
    dest:  /etc/telegraf/telegraf.d/telegraf_{{item}}.conf 
    owner: root 
    group: root
    mode:  "a+r"
  notify: restart telegraf
  with_items:    "{{ live_procs.list }}"
  failed_when:   false
  ignore_errors: true

